<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1248917699 - Wednesday, July 29, 2009, 08:34:59 PM CDT -0500
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Image download page title
		002 -- Error to be displayed when no filename is given to download
		003 -- Error to be displayed if the given file to download does not exist

*/
    
	$mmhclass->lang['001'] = "دریافت تصویر";
	$mmhclass->lang['002'] = "نام فایل وارد نشده است.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";
	$mmhclass->lang['003'] = "فایل تصویر <b>%s</b> یافت نشد.<br />
لطفا از درست بودن نام فایل اطمینان حاصل کنید.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";


?>