<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1251384545 - Thursday, August 27, 2009, 10:49:05 AM EDT -0400
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Default page title for home page
		002 -- Page title for URL upload page
		003 -- Allowed file extensions list grammatical conjuncture
		004 -- Message to be displayed when uploading is disabled
		005 -- Page title for when uploading is disabled
		006 -- Error to be displayed when no random image is found
		007 -- Message to be displayed when uploading is disabled for Guests

*/
    
	$mmhclass->lang['001'] = "آپلود عکس";
	$mmhclass->lang['002'] = "آپلود عکس آنلاین";
	$mmhclass->lang['003'] = "و";
	$mmhclass->lang['004'] = "در حال حاضر آپلود عکس غیر فعال است.<br />
 جهت اطلاعات بیشتر: <a href=\"contact.php?act=contact_us\">تماس با ما</a>.";
	$mmhclass->lang['005'] = "آپلود عکس غیر فعال است.";
	$mmhclass->lang['006'] = "هیچ تصویر آپلود یافت نشد.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";
	$mmhclass->lang['007'] = "با عرض پوزش، تنها کاربران مجاز به آپلود عکس هستند.<br />
لطفا یا عضو سایت شده یا وارد حساب کاربری خود شوید.";


?>