<?php
/* 
     // ======================================== \
     // Package: Mihalism Multi Host
     // Version: 5.0.0
     // Copyright (c) 2007, 2008, 2009 Mihalism Technologies
     // License: http://www.gnu.org/licenses/gpl.txt GNU Public License
     // LTE: 1251920869 - Wednesday, September 02, 2009, 03:47:49 PM EDT -0400
     // ======================================== /
     
     This file contains some language settings that are a part of Mihalism Multi Host but were not able to 
     be placed into template files. In each setting, %s represents a place holder for a value that will 
     be dynamically generated by Mihalism Multi Host; so be careful while editing to not remove them.
     
     Language file index:
		001 -- Page title for viewer page
		002 -- Error to be displayed if no filename is given
		003 -- Error to to displayed if the given filename does not exist
		004 -- Error to be displayed if an image cannot be displayed
		005 -- Error to be displayed if a person tries to rate an image multiple times
		006 -- Message to be displayed on a successful image rating submission

*/
    
	$mmhclass->lang['001'] = "تصاویر » %s";
	$mmhclass->lang['002'] = "لطفا نام فایل را با دقت وارد کنید.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";
	$mmhclass->lang['003'] = "تصویر  <b>%s</b> موجود نیست. <br />
لطفا از صحیح بودن نام فایل اطمینان حاصل کنید.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";
	$mmhclass->lang['004'] = "فایل درخواست شده یک تصویر قابل نمایش نیست. <br />
<a href=\"download.php?file=%s\">اینجا</a>کلیک کنید تا فایل را دریافت کنید.<br />
<br />
<a href=\"javascript:void(0);\" onclick=\"history.go(-1);\">بازگشت</a>";
	$mmhclass->lang['005'] = "شما قبلا به این تصویر امتیاز داده اید.";
	$mmhclass->lang['006'] = "امتیاز شما ثبت شد.<br />
<br />
<img src=\"index.php?module=rating&file=%s\" alt=\"File Rating\" />";


?>